//
// Created by 2ToThe10th on 02.04.2020.
//

#ifndef GAME_SRC_CLIENT_TCPSOCKETAGENT_TCPSOCKETAGENT_H_
#define GAME_SRC_CLIENT_TCPSOCKETAGENT_TCPSOCKETAGENT_H_

namespace Client::TCPSocketAgent {

class TCPSocketAgent {

};

}

#endif //GAME_SRC_CLIENT_TCPSOCKETAGENT_TCPSOCKETAGENT_H_
