//
// Created by 2ToThe10th on 02.04.2020.
//

#ifndef GAME_SRC_CLIENT_UDPSOCKETAGENT_UDPSOCKETAGENT_H_
#define GAME_SRC_CLIENT_UDPSOCKETAGENT_UDPSOCKETAGENT_H_

namespace Client::UDPSocketAgent {

class UDPSocketAgent {

};

}

#endif //GAME_SRC_CLIENT_UDPSOCKETAGENT_UDPSOCKETAGENT_H_
